name: Generate Contribution Calendar

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: write

jobs:
  calendar:
    runs-on: ubuntu-latest

    steps:
      - name: Generate labeled contribution calendar
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.calendar.svg
          token: ${{ github.token }}
          base: ""
          plugin_calendar: yes
          plugin_calendar_limit: 1
          output_action: commit
          committer_branch: output
